In [54]:
import pandas as pd
import numpy as np

In [55]:
data = pd.read_csv("Bikes.csv")
data.head()

bike_name     price       city  kms_driven  \
0    TVS Star City Plus Dual Tone 110cc   35000.0  Ahmedabad     17654.0   
1           Royal Enfield Classic 350cc  119900.0      Delhi     11000.0   
2                  Triumph Daytona 675R  600000.0      Delhi       110.0   
3                  TVS Apache RTR 180cc   65000.0  Bangalore     16329.0   
4  Yamaha FZ S V 2.0 150cc-Ltd. Edition   80000.0  Bangalore     10000.0   

         owner  age  power          brand  
0  First Owner  3.0  110.0            TVS  
1  First Owner  4.0  350.0  Royal Enfield  
2  First Owner  8.0  675.0        Triumph  
3  First Owner  4.0  180.0            TVS  
4  First Owner  3.0  150.0         Yamaha

In [56]:
data = data.drop(columns="city")

In [57]:
data.shape

(32648, 7)

In [58]:
data.isnull().mean()*100

bike_name     0.0
price         0.0
kms_driven    0.0
owner         0.0
age           0.0
power         0.0
brand         0.0
dtype: float64

In [59]:
data.duplicated().sum()

25332

In [60]:
data.drop_duplicates(inplace=True)

In [61]:
data.shape

(7316, 7)

In [62]:
data.head()

bike_name     price  kms_driven        owner  \
0    TVS Star City Plus Dual Tone 110cc   35000.0     17654.0  First Owner   
1           Royal Enfield Classic 350cc  119900.0     11000.0  First Owner   
2                  Triumph Daytona 675R  600000.0       110.0  First Owner   
3                  TVS Apache RTR 180cc   65000.0     16329.0  First Owner   
4  Yamaha FZ S V 2.0 150cc-Ltd. Edition   80000.0     10000.0  First Owner   

   age  power          brand  
0  3.0  110.0            TVS  
1  4.0  350.0  Royal Enfield  
2  8.0  675.0        Triumph  
3  4.0  180.0            TVS  
4  3.0  150.0         Yamaha

# DATA PREPROCESSING

In [63]:
data["bike_name"].unique()

array(['TVS Star City Plus Dual Tone 110cc',
       'Royal Enfield Classic 350cc', 'Triumph Daytona 675R',
       'TVS Apache RTR 180cc', 'Yamaha FZ S V 2.0 150cc-Ltd. Edition',
       'Yamaha FZs 150cc', 'Honda CB Hornet 160R  ABS DLX',
       'Hero Splendor Plus Self Alloy 100cc',
       'Royal Enfield Thunderbird X 350cc',
       'Royal Enfield Classic Desert Storm 500cc',
       'Yamaha YZF-R15 2.0 150cc', 'Yamaha FZ25 250cc',
       'Bajaj Pulsar NS200', 'Bajaj Discover 100M', 'Bajaj Discover 125M',
       'Bajaj Pulsar NS200 ABS', 'Bajaj Pulsar RS200 ABS',
       'Suzuki Gixxer SF 150cc', 'Benelli 302R 300CC',
       'Hero Splendor iSmart Plus IBS 110cc',
       'Royal Enfield Classic Chrome 500cc', 'Yamaha FZ V 2.0 150cc',
       'Hero Super Splendor 125cc', 'Honda CBF Stunner 125cc',
       'Bajaj Pulsar 150cc', 'Honda X-Blade 160CC ABS',
       'Bajaj Avenger 220cc', 'KTM RC 390cc', 'Honda CB Unicorn 150cc',
       'KTM Duke 200cc', 'Honda CBR 150R 150cc',
       'Royal Enfiel

In [64]:
data["bike_name"] = data["bike_name"].str.split(" ").str.slice(0,3).str.join(" ")

In [65]:
data.head()

bike_name     price  kms_driven        owner  age  power  \
0          TVS Star City   35000.0     17654.0  First Owner  3.0  110.0   
1  Royal Enfield Classic  119900.0     11000.0  First Owner  4.0  350.0   
2   Triumph Daytona 675R  600000.0       110.0  First Owner  8.0  675.0   
3         TVS Apache RTR   65000.0     16329.0  First Owner  4.0  180.0   
4            Yamaha FZ S   80000.0     10000.0  First Owner  3.0  150.0   

           brand  
0            TVS  
1  Royal Enfield  
2        Triumph  
3            TVS  
4         Yamaha

In [66]:
data["price"] = data["price"].astype(int)

In [67]:
data["kms_driven"].unique()

array([17654., 11000.,   110., ..., 48587.,  3430.,  7127.])

In [68]:
data["kms_driven"] =data["kms_driven"].astype(int)

In [69]:
data["owner"].unique()

array(['First Owner', 'Second Owner', 'Third Owner',
       'Fourth Owner Or More'], dtype=object)

In [70]:
data = data[data["owner"] != "Fourth Owner Or More"]
data["owner"] = data["owner"].str.split(" ").str.get(0)

In [71]:
data["age"].unique()

array([ 3.,  4.,  8.,  6.,  7.,  5.,  2., 16., 13.,  9., 10., 14., 12.,
       11.,  1., 15., 39., 17., 18., 30., 19., 23., 41., 27., 24., 20.,
       43., 37., 38., 63., 34., 31., 22., 26., 25.])

In [72]:
data["age"] = data["age"].astype(int)

In [73]:
data["power"].unique()

array([ 110.,  350.,  675.,  180.,  150.,  160.,  100.,  500.,  250.,
        200.,  125.,  302.,  220.,  390.,  600.,  900.,  650.,  223.,
        410.,  135., 1100.,  765.,  300., 1299.,  750.,  400., 1300.,
        821., 1198.,  883.,  959.,  295.,  320.,  310.,  899., 1800.,
        535., 1130., 1000., 1200., 1050.,  800., 1262., 1700.,  175.,
        865.,  797.,  796.,  149.,  850., 1090.,  502.,  107.])

In [74]:
data["power"] = data["power"].astype(int)

In [75]:
data["brand"].unique()

array(['TVS', 'Royal Enfield', 'Triumph', 'Yamaha', 'Honda', 'Hero',
       'Bajaj', 'Suzuki', 'Benelli', 'KTM', 'Mahindra', 'Kawasaki',
       'Ducati', 'Hyosung', 'Harley-Davidson', 'Jawa', 'BMW', 'Indian',
       'Rajdoot', 'LML', 'Yezdi', 'MV', 'Ideal'], dtype=object)

In [76]:
data = data[data["brand"] != "Indian"]
data = data[data["brand"] != "Ideal"]
data = data[data["brand"] != "MV"]
data = data[data["brand"] != "LML"]
data = data[data["brand"] != "Rajdoot"]

In [77]:
data.head()

bike_name   price  kms_driven  owner  age  power          brand
0          TVS Star City   35000       17654  First    3    110            TVS
1  Royal Enfield Classic  119900       11000  First    4    350  Royal Enfield
2   Triumph Daytona 675R  600000         110  First    8    675        Triumph
3         TVS Apache RTR   65000       16329  First    4    180            TVS
4            Yamaha FZ S   80000       10000  First    3    150         Yamaha

In [78]:
data.shape

(7297, 7)

In [79]:
data.duplicated().sum()

1

In [80]:
data.drop_duplicates(inplace=True)

In [81]:
data.isnull().mean()*100

bike_name     0.0
price         0.0
kms_driven    0.0
owner         0.0
age           0.0
power         0.0
brand         0.0
dtype: float64

In [82]:
data.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 7296 entries, 0 to 9372
Data columns (total 7 columns):
 #   Column      Non-Null Count  Dtype 
---  ------      --------------  ----- 
 0   bike_name   7296 non-null   object
 1   price       7296 non-null   int32 
 2   kms_driven  7296 non-null   int32 
 3   owner       7296 non-null   object
 4   age         7296 non-null   int32 
 5   power       7296 non-null   int32 
 6   brand       7296 non-null   object
dtypes: int32(4), object(3)
memory usage: 342.0+ KB


In [83]:
data.describe()

price     kms_driven          age        power
count  7.296000e+03    7296.000000  7296.000000  7296.000000
mean   8.396460e+04   23922.139940     6.639117   227.297012
std    1.162504e+05   27337.935799     3.533271   156.022383
min    5.000000e+03       1.000000     1.000000   100.000000
25%    3.000000e+04   10194.750000     4.000000   125.000000
50%    5.500000e+04   19000.000000     6.000000   160.000000
75%    1.000000e+05   30112.000000     8.000000   350.000000
max    1.800000e+06  750000.000000    63.000000  1700.000000

In [84]:
data = data[data["age"]<25]

In [85]:
data.shape

(7280, 7)

In [86]:
data = data.reset_index(drop=True)

In [87]:
data.head()

bike_name   price  kms_driven  owner  age  power          brand
0          TVS Star City   35000       17654  First    3    110            TVS
1  Royal Enfield Classic  119900       11000  First    4    350  Royal Enfield
2   Triumph Daytona 675R  600000         110  First    8    675        Triumph
3         TVS Apache RTR   65000       16329  First    4    180            TVS
4            Yamaha FZ S   80000       10000  First    3    150         Yamaha

In [88]:
data.to_csv("Clened_Bike_Details")

# MODEL BUILDING

In [89]:
from sklearn.compose import make_column_transformer
from sklearn.preprocessing import OneHotEncoder, MinMaxScaler
from sklearn.linear_model import LinearRegression
from sklearn.tree import DecisionTreeRegressor
from sklearn.ensemble import RandomForestRegressor
from sklearn.model_selection import train_test_split
from sklearn.pipeline import make_pipeline
from sklearn.metrics import r2_score
import pickle

In [90]:
ohe = OneHotEncoder()
ohe.fit(data[["bike_name", "owner","brand"]])
ohe.categories_

[array(['BMW F750 GS', 'BMW G 310', 'BMW S 1000', 'Bajaj  Pulsar',
        'Bajaj Avenger 150cc', 'Bajaj Avenger 180cc',
        'Bajaj Avenger 200cc', 'Bajaj Avenger 220cc',
        'Bajaj Avenger Cruise', 'Bajaj Avenger Street',
        'Bajaj Boxer AT100', 'Bajaj Boxer BM150', 'Bajaj Boxer CT100',
        'Bajaj CT 100', 'Bajaj CT110 ES', 'Bajaj Discover 100M',
        'Bajaj Discover 100T', 'Bajaj Discover 100cc',
        'Bajaj Discover 110cc', 'Bajaj Discover 125M',
        'Bajaj Discover 125ST', 'Bajaj Discover 125T',
        'Bajaj Discover 125cc', 'Bajaj Discover 135cc',
        'Bajaj Discover 150F', 'Bajaj Discover 150S',
        'Bajaj Discover 150cc', 'Bajaj Discover150 150cc',
        'Bajaj Discover150S 150cc', 'Bajaj Dominar 400', 'Bajaj Platina ',
        'Bajaj Platina 100cc', 'Bajaj Platina 110', 'Bajaj Platina 125cc',
        'Bajaj Platina Alloy', 'Bajaj Pulsar ', 'Bajaj Pulsar 125cc',
        'Bajaj Pulsar 135LS', 'Bajaj Pulsar 150cc', 'Bajaj Pulsar 180cc',
     

In [91]:
clmn_tfr = make_column_transformer((OneHotEncoder(categories=ohe.categories_), ["bike_name", "owner","brand"]),
                                   (MinMaxScaler(), ["age","kms_driven","power"]),
                                    remainder="passthrough")

In [92]:
x = data.drop(columns="price")
y = data["price"]
x.shape

(7280, 6)

In [93]:
score = []
for i in range(1001):
    x_train, x_test, y_train, y_test = train_test_split(x,y, test_size=0.2, random_state=i)
    lr = LinearRegression()
    pipe = make_pipeline(clmn_tfr,lr)
    pipe.fit(x_train,y_train)
    pred = pipe.predict(x_test)
    score.append(r2_score(y_test,pred))
print("i= ",np.argmax(score))
print(score[np.argmax(score)])

i=  689
0.9465001096953275


In [94]:
score = []
for i in range(1001):
    x_train, x_test, y_train, y_test = train_test_split(x,y, test_size=0.2, random_state=i)
    dt = DecisionTreeRegressor()
    pipe = make_pipeline(clmn_tfr,dt)
    pipe.fit(x_train,y_train)
    pred = pipe.predict(x_test)
    score.append(r2_score(y_test,pred))
print("i= ",np.argmax(score))
print(score[np.argmax(score)])

i=  447
0.9500230893203072


In [95]:
score = []
for i in range(50):
    x_train, x_test, y_train, y_test = train_test_split(x,y, test_size=0.2, random_state=i)
    rf = RandomForestRegressor()
    pipe = make_pipeline(clmn_tfr,rf)
    pipe.fit(x_train,y_train)
    pred = pipe.predict(x_test)
    score.append(r2_score(y_test,pred))
print("i= ",np.argmax(score))
print(score[np.argmax(score)])

i=  47
0.9534644687214723


In [96]:
x_train, x_test, y_train, y_test = train_test_split(x,y, test_size=0.2, random_state=47)
rf = RandomForestRegressor()
pipe = make_pipeline(clmn_tfr,rf)
pipe.fit(x_train,y_train)
pred = pipe.predict(x_test)
r2_score(y_test,pred)*100

95.11382976538715

In [97]:
pickle.dump(pipe,open("Bike_Price_Prediction.pkl","wb"))