In [1]:
import pandas as pd
import numpy as np

In [2]:
data = pd.read_csv("House Data.csv")
data.head()

area_type   availability       size  society total_sqft  bath  \
0  Super built-up  Area         19-Dec      2 BHK  Coomee        1056   2.0   
1            Plot  Area  Ready To Move  4 Bedroom  Theanmp       2600   5.0   
2        Built-up  Area  Ready To Move      3 BHK      NaN       1440   2.0   
3  Super built-up  Area  Ready To Move      3 BHK  Soiewre       1521   3.0   
4  Super built-up  Area  Ready To Move      2 BHK      NaN       1200   2.0   

   balcony   price    site_location  
0      1.0   39.07      Alandi Road  
1      3.0  120.00  Ambegaon Budruk  
2      3.0   62.00       Anandnagar  
3      1.0   95.00            Aundh  
4      1.0   51.00       Aundh Road

In [3]:
data = data.drop(columns=["area_type","society","availability"])

In [4]:
data.shape

(13320, 6)

In [5]:
data.isnull().mean()*100

size             0.120120
total_sqft       0.000000
bath             0.548048
balcony          4.572072
price            0.000000
site_location    0.007508
dtype: float64

In [6]:
data.dropna(inplace=True)

In [7]:
data.shape

(12710, 6)

# DATA PREPROCESSING

In [8]:
data.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 12710 entries, 0 to 13319
Data columns (total 6 columns):
 #   Column         Non-Null Count  Dtype  
---  ------         --------------  -----  
 0   size           12710 non-null  object 
 1   total_sqft     12710 non-null  object 
 2   bath           12710 non-null  float64
 3   balcony        12710 non-null  float64
 4   price          12710 non-null  float64
 5   site_location  12710 non-null  object 
dtypes: float64(3), object(3)
memory usage: 695.1+ KB


In [9]:
#data["availability"].unique()

In [10]:
#data = data[data["availability"] == 'Ready To Move']

In [11]:
data["size"].unique()

array(['2 BHK', '4 Bedroom', '3 BHK', '3 Bedroom', '1 BHK', '1 RK',
       '4 BHK', '1 Bedroom', '2 Bedroom', '6 Bedroom', '8 Bedroom',
       '7 Bedroom', '5 BHK', '7 BHK', '6 BHK', '5 Bedroom', '11 BHK',
       '9 BHK', '9 Bedroom', '27 BHK', '11 Bedroom', '43 Bedroom',
       '14 BHK', '8 BHK', '12 Bedroom', '10 Bedroom', '13 BHK'],
      dtype=object)

In [12]:
data["size"] = data["size"].str.split(" ").str.get(0).astype(int)

In [13]:
data["total_sqft"].unique()

array(['1056', '2600', '1440', ..., '1133 - 1384', '774', '4689'],
      dtype=object)

In [14]:
data["total_sqft"] = data["total_sqft"].str.split(" ").str.get(0)
data = data[data["total_sqft"].str.isnumeric()]
data["total_sqft"] = data["total_sqft"].astype(int)

In [15]:
data["bath"].unique()

array([ 2.,  5.,  3.,  4.,  1.,  8.,  7.,  6.,  9., 27., 11., 12., 10.,
       40., 15., 13.])

In [16]:
data["bath"] = data["bath"].astype(int)

In [17]:
data["balcony"].unique()

array([1., 3., 2., 0.])

In [18]:
data["balcony"] = data["balcony"].astype(int)

In [19]:
data["site_location"].unique()

array(['Alandi Road', 'Ambegaon Budruk', 'Anandnagar', 'Aundh',
       'Aundh Road', 'Balaji Nagar', 'Bhandarkar Road', 'Bibvewadi',
       'Bopodi', 'Budhwar Peth', 'Bund Garden Road', 'Camp',
       'Chandan Nagar', 'Dapodi', 'Deccan Gymkhana', 'Dehu Road',
       'Dhankawadi', 'Dhayari Phata', 'Dhole Patil Road', 'Erandwane',
       'Fatima Nagar', 'Fergusson College Road', 'Ganesh Peth',
       'Ganeshkhind', 'Ghorpade Peth', 'other', 'Gokhale Nagar',
       'Gultekdi', 'Guruwar peth', 'Hadapsar',
       'Hadapsar Industrial Estate', 'Jangali Maharaj Road',
       'Kalyani Nagar', 'Karve Nagar', 'Karve Road', 'Kasba Peth',
       'Khadaki', 'Khadki', 'Kharadi', 'Kondhwa Khurd', 'Koregaon Park',
       'Kothrud', 'Law College Road', 'Laxmi Road', 'Lulla Nagar',
       'Mahatma Gandhi Road', 'Mangalwar peth', 'Manik Bagh',
       'Market yard', 'Mukund Nagar', 'Mundhawa', 'Nagar Road',
       'Nana Peth', 'Narayan Peth', 'Narayangaon', 'Navi Peth',
       'Padmavati', 'Parvati Darsha

In [20]:
data = data[data["site_location"] != "other"]
data["site_location"] = data["site_location"].str.split(" ").str.slice(0,2).str.join(" ")

In [21]:
data["price"].unique()

array([ 39.07, 120.  ,  62.  , ...,  40.14, 231.  , 488.  ])

In [22]:
data["price"] = data["price"]*100000
data["price"] = data["price"].astype(int)

In [23]:
data.head()

size  total_sqft  bath  balcony     price    site_location
0     2        1056     2        1   3907000      Alandi Road
1     4        2600     5        3  12000000  Ambegaon Budruk
2     3        1440     2        3   6200000       Anandnagar
3     3        1521     3        1   9500000            Aundh
4     2        1200     2        1   5100000       Aundh Road

In [24]:
data.describe()

size    total_sqft          bath       balcony         price
count  12578.000000  12578.000000  12578.000000  12578.000000  1.257800e+04
mean       2.735729   1509.325648      2.614009      1.586421  1.057179e+07
std        1.205114   1164.113526      1.225054      0.817075  1.318765e+07
min        1.000000      5.000000      1.000000      0.000000  8.000000e+05
25%        2.000000   1100.000000      2.000000      1.000000  4.900000e+06
50%        3.000000   1258.000000      2.000000      2.000000  7.000000e+06
75%        3.000000   1636.000000      3.000000      2.000000  1.147500e+07
max       43.000000  52272.000000     40.000000      3.000000  2.912000e+08

In [25]:
data.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 12578 entries, 0 to 13319
Data columns (total 6 columns):
 #   Column         Non-Null Count  Dtype 
---  ------         --------------  ----- 
 0   size           12578 non-null  int32 
 1   total_sqft     12578 non-null  int32 
 2   bath           12578 non-null  int32 
 3   balcony        12578 non-null  int32 
 4   price          12578 non-null  int32 
 5   site_location  12578 non-null  object
dtypes: int32(5), object(1)
memory usage: 442.2+ KB


In [26]:
data.duplicated().sum()

34

In [27]:
data.drop_duplicates(inplace=True)

In [28]:
data.shape

(12544, 6)

In [29]:
data.head()

size  total_sqft  bath  balcony     price    site_location
0     2        1056     2        1   3907000      Alandi Road
1     4        2600     5        3  12000000  Ambegaon Budruk
2     3        1440     2        3   6200000       Anandnagar
3     3        1521     3        1   9500000            Aundh
4     2        1200     2        1   5100000       Aundh Road

In [30]:
data.to_csv("Cleane_House_Details.csv")

# MODEL BUILDING

In [31]:
from sklearn.compose import make_column_transformer
from sklearn.preprocessing import OneHotEncoder, MinMaxScaler
from sklearn.linear_model import LinearRegression
from sklearn.tree import DecisionTreeRegressor
from sklearn.ensemble import RandomForestRegressor
from sklearn.model_selection import train_test_split, cross_val_score
from sklearn.pipeline import make_pipeline
from sklearn.metrics import r2_score
import pickle

In [32]:
ohe = OneHotEncoder()
ohe.fit(data[["site_location"]])
ohe.categories_

[array(['Alandi Road', 'Ambegaon Budruk', 'Anandnagar', 'Aundh',
        'Aundh Road', 'Balaji Nagar', 'Baner', 'Baner road',
        'Bhandarkar Road', 'Bhavani Peth', 'Bibvewadi', 'Bopodi',
        'Budhwar Peth', 'Bund Garden', 'Camp', 'Chandan Nagar', 'Dapodi',
        'Deccan Gymkhana', 'Dehu Road', 'Dhankawadi', 'Dhayari Phata',
        'Dhole Patil', 'Erandwane', 'Fatima Nagar', 'Fergusson College',
        'Ganesh Peth', 'Ganeshkhind', 'Ghorpade Peth', 'Ghorpadi',
        'Gokhale Nagar', 'Gultekdi', 'Guruwar peth', 'Hadapsar',
        'Hadapsar Industrial', 'Hingne Khurd', 'Jangali Maharaj',
        'Kalyani Nagar', 'Karve Nagar', 'Karve Road', 'Kasba Peth',
        'Katraj', 'Khadaki', 'Khadki', 'Kharadi', 'Kondhwa',
        'Kondhwa Budruk', 'Kondhwa Khurd', 'Koregaon Park', 'Kothrud',
        'Law College', 'Laxmi Road', 'Lulla Nagar', 'Mahatma Gandhi',
        'Mangalwar peth', 'Manik Bagh', 'Market yard', 'Model colony',
        'Mukund Nagar', 'Mundhawa', 'Nagar Road', '

In [33]:
clmn_tfr = make_column_transformer((OneHotEncoder(categories=ohe.categories_), ["site_location"]),
                                   (MinMaxScaler(), ["size","total_sqft","bath","balcony"]),
                                      remainder="passthrough")

In [34]:
x = data.drop(columns="price")
y = data["price"]

In [35]:
score = []
for i in range(1001):
    x_train, x_test, y_train, y_test = train_test_split(x,y, test_size=0.2, random_state=i)
    lr = LinearRegression()
    pipe = make_pipeline(clmn_tfr,lr)
    pipe.fit(x_train,y_train)
    pred = pipe.predict(x_test)
    score.append(r2_score(y_test,pred))
print("i= ",np.argmax(score))
print(score[np.argmax(score)])

i=  817
0.5426704427542004


In [36]:
score = []
for i in range(50):
    x_train, x_test, y_train, y_test = train_test_split(x,y, test_size=0.2, random_state=i)
    dt = DecisionTreeRegressor()
    pipe = make_pipeline(clmn_tfr,dt)
    pipe.fit(x_train,y_train)
    pred = pipe.predict(x_test)
    score.append(r2_score(y_test,pred))
print("i= ",np.argmax(score))
print(score[np.argmax(score)])

i=  22
0.5036964446755343


In [37]:
score = []
for i in range(10):
    x_train, x_test, y_train, y_test = train_test_split(x,y, test_size=0.2, random_state=i)
    rf = RandomForestRegressor()
    pipe = make_pipeline(clmn_tfr,rf)
    pipe.fit(x_train,y_train)
    pred = pipe.predict(x_test)
    score.append(r2_score(y_test,pred))
print("i= ",np.argmax(score))
print(score[np.argmax(score)])

i=  7
0.6504888164606754


In [41]:
x_train, x_test, y_train, y_test = train_test_split(x,y, test_size=0.2, random_state=7)
rf = RandomForestRegressor(n_estimators=500)
pipe = make_pipeline(clmn_tfr,rf)
pipe.fit(x_train,y_train)
pred = pipe.predict(x_test)
r2_score(y_test,pred)*100

65.18074193406396

In [42]:
#Eg
pipe.predict(pd.DataFrame([[4,1450,4,2,"Dhankawadi"]], columns=["size","total_sqft","bath","balcony","site_location"]))

array([15381132.])

In [43]:
pickle.dump(pipe,open("House_Price_Prediction.pkl","wb"))